backend:
  name: git-gateway
  branch: master
media_folder: static
public_folder: /
collections:
  - name: "content"
    label: "Content"
    folder: "content"
    create: false
    editor:
      preview: false
    fields:
      - label: "Body"
        name: "body"
        widget: "markdown"
