# yaml-language-server: $schema=https://json.schemastore.org/netlify.json

backend:
  name: git-gateway
  branch: master
media_folder: static
media_library:
  name: 'disabled'
public_folder: /
collections:
  - name: "content"
    label: "Content"
    folder: "content"
    create: false
    editor:
      preview: false
    fields:
      - label: "Body"
        name: "body"
        widget: "markdown"
