[[rooms]]
name = "Main Hall"
size = "42'x70'<br>940ft&sup2;"
seating = "249 banquet style<br>366 theatre style"

[[rooms]]
name = "Lobby"
size = "18'x20'<br>720ft&sup2;"
seating = "40 reception style"

[[rooms]]
name = "Room #2"
size = "22'x43'<br>946ft&sup2;"
seating = "60 banquet style<br>100 theatre style"

[[rooms]]
name = "Boardroom"
size = "17'3\"x 21'7\"<br>372ft&sup2;"
seating = "25 conference style"
